version: "2"
services:
    portainer:
        restart: always
        image: portainer/portainer
        container_name: "portainer-app"
        ports:
            - "9000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /opt/portainer/data:/data
    couchpotato:
        restart: always
        container_name: couchPotato
        image: linuxserver/couchpotato
        ports:
            - "5050:5050"
        volumes:
            - /opt/couchpotato:/config
            - /storage/downloads:/downloads
            - /storage/data/movies:/movies
        environment:
            - PUID=1000
            - PGID=1000
            - UMAST_SET=<022>
        network_mode: host
    deluge:
        restart: always
        container_name: deluge
        ports:
            - "8112:8112"
        image: linuxserver/deluge
        volumes:
            - /storage/downloads:/downloads
            - /opt/deluge:/config
            - /storage/data/TV:/tv
            - /storage/data/movies:/movies
            - /storage/data/4k:/4k
            - /storage/completed:/completed
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            - UMAST_SET=<022>
    plex:
        restart: always
        image: plexinc/pms-docker
        container_name: "plex.tv"
        ports:
            - "32400:32400"
        volumes:
            - /storage/plex/config:/config
            - /storage/plex/transcode/temp:/transcode
            - /storage/data/movies:/movies
            - /storage/data/TV:/TV
            - /storage/data/4k:/4k
        environment:
            - TZ="europe/london"
        network_mode: host
    jackett:
        restart: always
        image: linuxserver/jackett
        container_name: "jackett"
        ports:
                - "9117:9117"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /storage/jacket/config:/config
            - /storage/downloads:/downloads
        environment:
            - TZ="europe/london"
            - PUID=1000
            - PGID=1000
        network_mode: host
    sonarr:
        restart: always
        image: linuxserver/sonarr
        ports:
            - "8989:8989"
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /storage/sonarr/config:/config
            - /storage/data/TV:/tv
            - /storage/downloads:/downloads
        network_mode: host
    watchtower:
        restart: always
        image: v2tec/watchtower
        container_name: "portainer-watchtower"
        command: --cleanup portainer-app portainer-watchtower portainer/templates
        networks:
            - local
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
networks:
    local:
        driver: bridge
