version: "2"
services:
    proxy:
        build: nginx/
        container_name: "portainer-proxy"
        ports:
            - "80:80"
        networks:
            - local
    templates:
        image: portainer/templates
        container_name: "portainer-templates"
        networks:
            - local
    portainer:
        image: portainer/portainer
        container_name: "portainer-app"
        command: --templates http://templates/templates.json
        networks:
            - local
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /opt/portainer/data:/data
    couchpotato:
        restart: always
        container_name: couchPotato
        image: linuxserver/couchpotato
        ports:
            - "5050:5050"
        volumes:
            - /opt/couchpotato:/config
            - /storage/downloads:/downloads
            - /storage/movies:/movies
        environment:
            - PUID=1000
            - PGID=1000
            - UMAST_SET=<022>
        network_mode: host
    nzbget:
        restart: always
        container_name: nzbGET
        image: linuxserver/nzbget
        ports:
            - "6789:6789"
        volumes:
            - /opt/nzbget:/config
            - /storage/downloads:/downloads
            - /storage/TV:/tv
            - /storage/movies:/movies
            - /storage/4k:/4k
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
    deluge:
        restart: always
        container_name: deluge
        ports:
            - "8112:8112"
        image: linuxserver/deluge
        volumes:
            - /storage/downloads:/downloads
            - /opt/deluge:/config
            - /storage/TV:/tv
            - /storage/movies:/movies
            - /storage/4k:/4k
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            - UMAST_SET=<022>
    watchtower:
        image: v2tec/watchtower
        container_name: "portainer-watchtower"
        command: --cleanup portainer-app portainer-watchtower portainer/templates
        networks:
            - local
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
networks:
    local:
        driver: bridge
