version: "2"
services:
    plex:
        image: plexinc/pms-docker
        container_name: "plex.tv"
        ports:
            - "32400:32400"
        volumes:
            - /storage/plex/config:/config
            - /storage/plex/transcode/temp:/transcode
            - /storage/plex/data/movies:/movies
            - /storage/plex/data/TV:/TV
            - /storage/plex/data/4k:/4k
        environment:
            - TZ="europe/london"
        network_mode: host
