#!/bin/bash

## Media server setup script
echo
echo "Media Server Setup Script - MSSS"
echo "================================"
echo
# 1. Check directories exist
echo "1. Check storage"
echo "----------------"
echo
# Find all storage paths in the compose file, will change this at some point to auto find the volumes even without /storage as the root

DIRS=`grep storage docker-compose.yml | tr -d ' ' | sort -u | cut -d ":" -f 1 | tr -d '-'`

while read line
do
	echo "Working with $line"
	if [ ! -d "$line" ]
	then
		echo -e "\t$line doesn't exists, creating..."
		mkdir -p $line
	else
		echo -e "\t$line exists, moving on..."
	fi

done <<< "$DIRS"

# 2. Check docker utils, install if needed

DOCKER_INSTALL=""
echo
echo "2. Checking docker utils"
echo "------------------------"
echo
docker version > /dev/null 2>&1
if [[ $? != 0 ]]
then
	echo -e "\tdocker missing, adding to install list"
	DOCKERINSTALL="docker"
fi

docker-compose version > /dev/null 2>&1
if [[ $? != 0 ]]
then
	echo -e "\tdocker-compose missing, adding to install list"
        DOCKERINSTALL="$DOCKERINSTALL docker-compose"
fi

if [ "$DOCKERINSTALL" == "" ]
then
	echo "Docker is installed, move along"
else
	echo "Installing missing docker utils"
	echo "apt-get -yqq update; apt-get -yqq install $DOCKERINSTALL"
fi

# 3. Update rc.local if needed

echo
echo "3. Checking boot up of docker"
echo "-----------------------------"
echo

grep $PWD/docker-compose.yml /etc/rc.local > /dev/null 2>&1 
if [[ $? != 0 ]]
then
	echo -e "\tMissing launcher, adding now..."
	echo "" >> /etc/rc.local
	echo "## Starting media server - added by $PWD/setup" >> rc.local
	echo "docker-compose -f $PWD/docker-compose.yml up -d" >> /etc/rc.local
	echo 
else
	echo -e "\tLauncher is OK, moving on."
fi

# 4. All done, ask if we want to run it
echo
echo "Work complete."
echo "=============="
echo

while true; do
    read -p "Shall I start the containers now? [Y]es [N]o " yn
    case $yn in
        [Yy]* ) echo -e "\tLaunching MSSS"; docker-compose -f $PWD/docker-compose.yml up -d; break;;
        [Nn]* ) echo ; echo "No worries, run this to start or reboot"; echo -e "\tdocker-compose -f $PWD/docker-compose.yml up -d"; exit;;
        * ) echo "Please answer yes or no.";;
    esac
done
